services:
  mycassa:
    networks:
      - mysagra
      - default
    build: .
    env_file: .env
    ports:
      - "7000:7000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - API_URL=${API_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=${AUTH_URL}
    restart: unless-stopped

networks:
  mysagra:
    name: mysagra_network
    external: true
